<?php

/**
 *
 * @author Lunalol - PERRIN Jean-Luc
 *
 */
class Board extends APP_GameClass
{
//
// Regions (44)
//
	const REGIONS = [
		BULGARIA => ['type' => LAND, 1941],
		BOSPORUS => ['type' => WATER],
		ADRIATICSEA => ['type' => WATER],
		YUGOSLAVIA => ['type' => LAND, 'VP' => 1, 1941],
		BLACKSEA => ['type' => WATER],
		TRIESTE => ['type' => LAND, 1941],
		ROMANIA => ['type' => LAND, 'VP' => 1, 1941],
		SEVASTOPOL => ['type' => LAND, 'VP' => 1],
		HUNGARY => ['type' => LAND, 'VP' => 1, 1941],
		BESSARABIA => ['type' => LAND, 1939],
		SEAOFAZOV => ['type' => WATER],
		VIENNA => ['type' => LAND, 1941],
		CAUCASUS => ['type' => LAND, 'VP' => 1],
		DNIEPRRIVER => ['type' => WATER],
		KIEV => ['type' => LAND, 'VP' => 1],
		LWOW => ['type' => LAND, 1939],
		VOLGARIVER => ['type' => WATER],
		STALINGRAD => ['type' => LAND, 'VP' => 1],
		ROSTOV => ['type' => LAND],
		KHARKOV => ['type' => LAND],
		MOGILEV => ['type' => LAND],
		WARSAW => ['type' => LAND, 'VP' => 1, 1941],
		BERLIN => ['type' => LAND, 'VP' => 1, 1941],
		EASTPRUSSIA => ['type' => LAND, 'VP' => 1, 1941],
		BREST => ['type' => LAND, 1939],
		KURSK => ['type' => LAND],
		WESTBALTICSEA => ['type' => WATER],
		VORONEZH => ['type' => LAND, 'VP' => 1],
		SMOLENSK => ['type' => LAND, 'VP' => 1],
		LAKEPEIPUS => ['type' => WATER],
		BALTICSTATES => ['type' => LAND, 1939],
		MOSCOW => ['type' => LAND, 'VP' => 2],
		RYBINSKSEA => ['type' => WATER],
		GULFOFFINLAND => ['type' => WATER],
		NOVGOROD => ['type' => LAND],
		GORKI => ['type' => LAND],
		LENINGRAD => ['type' => LAND, 'VP' => 1],
		LAKELADOGA => ['type' => WATER],
		PETROZAVODSK => ['type' => LAND],
		VOLOGDA => ['type' => LAND, 'VP' => 1],
		LAKEONEGA => ['type' => WATER],
		KARELIA => ['type' => LAND, 1939],
		FINLAND => ['type' => LAND, 'VP' => 1, 1941],
		BALTICSEA => ['type' => WATER],
	];
//
// Adjacency  matrix
//
	const ADJACENCY = [
		BULGARIA => [YUGOSLAVIA, ROMANIA, BOSPORUS],
		BOSPORUS => [BULGARIA, ROMANIA, BLACKSEA],
		ADRIATICSEA => [TRIESTE, YUGOSLAVIA],
		YUGOSLAVIA => [ADRIATICSEA, TRIESTE, VIENNA, HUNGARY, ROMANIA, BULGARIA],
		BLACKSEA => [BOSPORUS, ROMANIA, BESSARABIA, SEVASTOPOL, SEAOFAZOV],
		TRIESTE => [ADRIATICSEA, YUGOSLAVIA, VIENNA],
		ROMANIA => [BULGARIA, YUGOSLAVIA, HUNGARY, LWOW, BESSARABIA, BLACKSEA, BOSPORUS],
		SEVASTOPOL => [BLACKSEA, SEAOFAZOV, ROSTOV, KIEV, BESSARABIA],
		HUNGARY => [YUGOSLAVIA, ROMANIA, LWOW, WARSAW, BERLIN, VIENNA],
		BESSARABIA => [ROMANIA, BLACKSEA, SEVASTOPOL, KIEV, LWOW],
		SEAOFAZOV => [CAUCASUS, ROSTOV, SEVASTOPOL, BLACKSEA],
		VIENNA => [TRIESTE, YUGOSLAVIA, HUNGARY, BERLIN],
		CAUCASUS => [STALINGRAD, ROSTOV, SEAOFAZOV],
		DNIEPRRIVER => [ROSTOV, KHARKOV, KIEV],
		KIEV => [SEVASTOPOL, DNIEPRRIVER, KHARKOV, MOGILEV, LWOW, BESSARABIA],
		LWOW => [ROMANIA, BESSARABIA, KIEV, MOGILEV, BREST, WARSAW, HUNGARY],
		VOLGARIVER => [STALINGRAD, GORKI, ROSTOV],
		STALINGRAD => [CAUCASUS, GORKI, VOLGARIVER, ROSTOV],
		ROSTOV => [SEAOFAZOV, CAUCASUS, STALINGRAD, VOLGARIVER, GORKI, VORONEZH, KHARKOV, DNIEPRRIVER, SEVASTOPOL],
		KHARKOV => [DNIEPRRIVER, ROSTOV, VORONEZH, KURSK, MOGILEV, KIEV],
		MOGILEV => [KIEV, KHARKOV, KURSK, SMOLENSK, BREST, LWOW],
		WARSAW => [HUNGARY, LWOW, BREST, EASTPRUSSIA, WESTBALTICSEA, BERLIN],
		BERLIN => [VIENNA, HUNGARY, WARSAW, WESTBALTICSEA],
		EASTPRUSSIA => [WARSAW, BREST, BALTICSTATES, BALTICSEA, WESTBALTICSEA],
		BREST => [LWOW, MOGILEV, SMOLENSK, BALTICSTATES, EASTPRUSSIA, WARSAW],
		KURSK => [KHARKOV, VORONEZH, MOSCOW, SMOLENSK, MOGILEV],
		WESTBALTICSEA => [BERLIN, WARSAW, EASTPRUSSIA, BALTICSEA],
		VORONEZH => [ROSTOV, GORKI, MOSCOW, KURSK, KHARKOV],
		SMOLENSK => [MOGILEV, KURSK, MOSCOW, NOVGOROD, LAKEPEIPUS, BALTICSTATES, BREST],
		LAKEPEIPUS => [BALTICSTATES, SMOLENSK, NOVGOROD, LENINGRAD],
		BALTICSTATES => [BREST, SMOLENSK, LAKEPEIPUS, LENINGRAD, GULFOFFINLAND, BALTICSEA, EASTPRUSSIA],
		MOSCOW => [KURSK, VORONEZH, GORKI, VOLOGDA, RYBINSKSEA, NOVGOROD, SMOLENSK],
		RYBINSKSEA => [MOSCOW, VOLOGDA, PETROZAVODSK, NOVGOROD],
		GULFOFFINLAND => [BALTICSTATES, LENINGRAD, KARELIA, FINLAND, BALTICSEA],
		NOVGOROD => [SMOLENSK, MOSCOW, RYBINSKSEA, PETROZAVODSK, LAKELADOGA, LENINGRAD, LAKEPEIPUS],
		GORKI => [VOLGARIVER, STALINGRAD, VOLOGDA, MOSCOW, VORONEZH, ROSTOV],
		LENINGRAD => [LAKEPEIPUS, NOVGOROD, LAKELADOGA, KARELIA, GULFOFFINLAND, BALTICSTATES],
		LAKELADOGA => [NOVGOROD, PETROZAVODSK, KARELIA, LENINGRAD],
		PETROZAVODSK => [NOVGOROD, RYBINSKSEA, VOLOGDA, LAKEONEGA, KARELIA, LAKELADOGA],
		VOLOGDA => [MOSCOW, GORKI, LAKEONEGA, PETROZAVODSK, RYBINSKSEA],
		LAKEONEGA => [PETROZAVODSK, VOLOGDA, KARELIA],
		KARELIA => [LAKELADOGA, PETROZAVODSK, LAKEONEGA, FINLAND, GULFOFFINLAND, LENINGRAD],
		FINLAND => [GULFOFFINLAND, KARELIA, BALTICSEA],
		BALTICSEA => [WESTBALTICSEA, EASTPRUSSIA, BALTICSTATES, GULFOFFINLAND, FINLAND],
	];
//
// Supply sources (4 + 2 + 5)
//
	const SUPPLY = [
		Factions::SOVIETUNION => [VOLOGDA, GORKI, STALINGRAD, CAUCASUS],
		Factions::GERMANY => [BERLIN, VIENNA],
		Factions::PACT => [FINLAND, BERLIN, TRIESTE, HUNGARY, ROMANIA],
	];
}
